language: node_js
node_js:
  - "10"
branches:
  only:
    - "master"
    - "spotify-wrapper"
cache:
  directories:
    - "node_modules"
before_script:
    - "npm run build:all"
after_success:
    - "npm run coveralls"
